### ISSUE TITLE
Rebuild for 1.20.x?

### ISSUE THREAD

**Issue by bentterp** [HyperPigeon/BeeDance#2]
Hi! I'd love to try out your mod, could you please make a rebuild for 1.20.x? It crashes with 1.20.1:
```
[06:56:18] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED beedance 1.1.0 {depends minecraft @ [1.20]}, ROOT_FORCELOAD_SINGLE beedance 1.1.0]
[06:56:18] [main/INFO]: Reason: [HARD_DEP beedance 1.1.0 {depends minecraft @ [1.20]}]
[06:56:18] [main/INFO]: Fix: add [], remove [], replace [[beedance 1.1.0] -> add:beedance 1 ([(-?,?)])]
[06:56:18] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'BeeDance' (beedance) 1.1.0 with any version that is compatible with:
		 - minecraft 1.20.1
Unmet dependency listing:
	 - Mod 'BeeDance' (beedance) 1.1.0 requires version 1.20 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?]
Process exited with code 1.
```

**Comment by HyperPigeon** [comment]
Sorry for the delay, fixed in the latest patch.
